 javaaddpath('C:\Users\Nero\Desktop\Berkeley\231A\HW2\smap-master\smap-master\java\JavaSmap_0.1.jar')
javaaddpath(['C:\Users\Nero\Desktop\Berkeley\231A\HW2\smap-master\smap-master\java\' ...
'JavaSmap\lib\javax.json-1.0-b06.jar'])
javaaddpath(['C:\Users\Nero\Desktop\Berkeley\231A\HW2\smap-master\smap-master\java\' ...
'JavaSmap\lib\json-simple-1.1.1.jar'])